// all currencies for select box
export const currencies = [
    {
        id: 2781,
        name: "دلار ایالات متحده",
        sign: "$",
        symbol: "USD",
    },
    {
        id: 2782,
        name: "دلار استرالیا",
        sign: "$",
        symbol: "AUD",
    },
    {
        id: 2783,
        name: "رئال برزیل",
        sign: "R$",
        symbol: "BRL",
    },
    {
        id: 2784,
        name: "دلار کانادا",
        sign: "$",
        symbol: "CAD",
    },
    {
        id: 2785,
        name: "فرانک سوئیس",
        sign: "فر",
        symbol: "CHF",
    },
    {
        id: 2786,
        name: "پزوی شیلی",
        sign: "$",
        symbol: "CLP",
    },
    {
        id: 2787,
        name: "یوان چین",
        sign: "¥",
        symbol: "CNY",
    },
    {
        id: 2788,
        name: "کرون چک",
        sign: "Kč",
        symbol: "CZK",
    },
    {
        id: 2789,
        name: "کرون دانمارک",
        sign: "kr",
        symbol: "DKK",
    },
    {
        id: 2790,
        name: "یورو",
        sign: "€",
        symbol: "EUR",
    },
    {
        id: 2791,
        name: "پوند استرلینگ",
        sign: "£",
        symbol: "GBP",
    },
    {
        id: 2792,
        name: "دلار هنگ کنگ",
        sign: "$",
        symbol: "HKD",
    },
    {
        id: 2793,
        name: "فورنت مجارستان",
        sign: "فوت",
        symbol: "HUF",
    },
    {
        id: 2794,
        name: "روپیه اندونزی",
        sign: "Rp",
        symbol: "IDR",
    },
    {
        id: 2795,
        name: "شکل جدید اسرائیل",
        sign: "₪",
        symbol: "ILS",
    },
    {
        id: 2796,
        name: "روپیه هند",
        sign: "₹",
        symbol: "INR",
    },
    {
        id: 2797,
        name: "ین ژاپن",
        sign: "¥",
        symbol: "JPY",
    },
    {
        id: 2798,
        name: "وون کره جنوبی",
        sign: "₩",
        symbol: "KRW",
    },
    {
        id: 2799,
        name: "پزوی مکزیکی",
        sign: "$",
        symbol: "MXN",
    },
    {
        id: 2800,
        name: "رینگیت مالزی",
        sign: "RM",
        symbol: "MYR",
    },
    {
        id: 2801,
        name: "کرون نروژ",
        sign: "kr",
        symbol: "NOK",
    },
    {
        id: 2802,
        name: "دلار نیوزلند",
        sign: "$",
        symbol: "NZD",
    },
    {
        id: 2803,
        name: "پزوی فیلیپین",
        sign: "₱",
        symbol: "PHP",
    },
    {
        id: 2804,
        name: "روپیه پاکستان",
        sign: "₨",
        symbol: "PKR",
    },
    {
        id: 2805,
        name: "Złoty لهستانی",
        sign: "zł",
        symbol: "PLN",
    },
    {
        id: 2806,
        name: "روبل روسیه",
        sign: "₽",
        symbol: "RUB",
    },
    {
        id: 2807,
        name: "کرون سوئد",
        sign: "kr",
        symbol: "SEK",
    },
    {
        id: 2808,
        name: "دلار سنگاپور",
        sign: "S$",
        symbol: "SGD",
    },
    {
        id: 2809,
        name: "بات تایلند",
        sign: "฿",
        symbol: "THB",
    },
    {
        id: 2810,
        name: "لیره ترکیه",
        sign: "₺",
        symbol: "TRY",
    },
    {
        id: 2811,
        name: "دلار جدید تایوان",
        sign: "NT$",
        symbol: "TWD",
    },
    {
        id: 2812,
        name: "راند آفریقای جنوبی",
        sign: "R",
        symbol: "ZAR",
    },
    {
        id: 2813,
        name: "درهم امارات متحده عربی",
        sign: "د.إ",
        symbol: "AED",
    },
    {
        id: 2814,
        name: "لو بلغاری",
        sign: "лв",
        symbol: "BGN",
    },
    {
        id: 2815,
        name: "کونا کرواسی",
        sign: "kn",
        symbol: "HRK",
    },
    {
        id: 2816,
        name: "روپیه موریس",
        sign: "₨",
        symbol: "MUR",
    },
    {
        id: 2817,
        name: "لئو رومانیایی",
        sign: "لی",
        symbol: "RON",
    },
    {
        id: 2818,
        name: "کرون ایسلند",
        sign: "kr",
        symbol: "ISK",
    },
    {
        id: 2819,
        name: "نایرا نیجریه",
        sign: "₦",
        symbol: "NGN",
    },
    {
        id: 2820,
        name: "پزوی کلمبیا",
        sign: "$",
        symbol: "COP",
    },
    {
        id: 2821,
        name: "پزوی آرژانتین",
        sign: "$",
        symbol: "ARS",
    },
    {
        id: 2822,
        name: "پرو سول",
        sign: "S/.",
        symbol: "PEN",
    },
    {
        id: 2823,
        name: "دونگ ویتنام",
        sign: "₫",
        symbol: "VND",
    },
    {
        id: 2824,
        name: "Hryvnia اوکراین",
        sign: "₴",
        symbol: "UAH",
    },
    {
        id: 2832,
        name: "بولیویانو بولیوی",
        sign: "Bs.",
        symbol: "BOB",
    },
    {
        id: 3526,
        name: "لک آلبانی",
        sign: "L",
        symbol: "ALL",
    },
    {
        id: 3527,
        name: "درام ارمنستان",
        sign: "֏",
        symbol: "AMD",
    },
    {
        id: 3528,
        name: "منات آذربایجان",
        sign: "₼",
        symbol: "AZN",
    },
    {
        id: 3529,
        name: "مارک قابل تبدیل بوسنی و هرزگوین",
        sign: "KM",
        symbol: "BAM",
    },
    {
        id: 3530,
        name: "تاکا بنگلادشی",
        sign: "৳",
        symbol: "BDT",
    },
    {
        id: 3531,
        name: "دینار بحرین",
        sign: ".د.ب",
        symbol: "BHD",
    },
    {
        id: 3532,
        name: "دلار برمودا",
        sign: "$",
        symbol: "BMD",
    },
    {
        id: 3533,
        name: "روبل بلاروس",
        sign: "Br",
        symbol: "BYN",
    },
    {
        id: 3534,
        name: "کاستاریکا کولون",
        sign: "₡",
        symbol: "CRC",
    },
    {
        id: 3535,
        name: "پزوی کوبا",
        sign: "$",
        symbol: "CUP",
    },
    {
        id: 3536,
        name: "پزوی دومینیکن",
        sign: "$",
        symbol: "DOP",
    },
    {
        id: 3537,
        name: "دینار الجزایر",
        sign: "د.ج",
        symbol: "DZD",
    },
    {
        id: 3538,
        name: "پوند مصر",
        sign: "£",
        symbol: "EGP",
    },
    {
        id: 3539,
        name: "لاری گرجستان",
        sign: "₾",
        symbol: "GEL",
    },
    {
        id: 3540,
        name: "سدی غنا",
        sign: "₵",
        symbol: "GHS",
    },
    {
        id: 3541,
        name: "کوئتزال گواتمالا",
        sign: "Q",
        symbol: "GTQ",
    },
    {
        id: 3542,
        name: "لمپیرا هندوراس",
        sign: "L",
        symbol: "HNL",
    },
    {
        id: 3543,
        name: "دینار عراق",
        sign: "«ع.د»",
        symbol: "IQD",
    },
    {
        id: 3544,
        name: "ریال ایران",
        sign: "﷼",
        symbol: "IRR",
    },
    {
        id: 3545,
        name: "دلار جامائیکا",
        sign: "$",
        symbol: "JMD",
    },
    {
        id: 3546,
        name: "دینار اردن",
        sign: "د.ا",
        symbol: "JOD",
    },
    {
        id: 3547,
        name: "شیلینگ کنیا",
        sign: "ش",
        symbol: "KES",
    },
    {
        id: 3548,
        name: "سوم قرقیزستانی",
        sign: "с",
        symbol: "KGS",
    },
    {
        id: 3549,
        name: "ریل کامبوج",
        sign: "៛",
        symbol: "KHR",
    },
    {
        id: 3550,
        name: "دینار کویت",
        sign: "د.ک",
        symbol: "KWD",
    },
    {
        id: 3551,
        name: "تنگه قزاقستانی",
        sign: "₸",
        symbol: "KZT",
    },
    {
        id: 3552,
        name: "پوند لبنان",
        sign: "ل.ل",
        symbol: "LBP",
    },
    {
        id: 3553,
        name: "روپیه سریلانکا",
        sign: "Rs",
        symbol: "LKR",
    },
    {
        id: 3554,
        name: "درهم مراکش",
        sign: "د.م.",
        symbol: "MAD",
    },
    {
        id: 3555,
        name: "لئو مولداوی",
        sign: "L",
        symbol: "MDL",
    },
    {
        id: 3556,
        name: "دنار مقدونیه",
        sign: "دن",
        symbol: "MKD",
    },
    {
        id: 3557,
        name: "میانمار کیات",
        sign: "Ks",
        symbol: "MMK",
    },
    {
        id: 3558,
        name: "توگریک مغولی",
        sign: "₮",
        symbol: "MNT",
    },
    {
        id: 3559,
        name: "دلار نامیبیا",
        sign: "$",
        symbol: "NAD",
    },
    {
        id: 3560,
        name: "کوردوبا نیکاراگوئه",
        sign: "C$",
        symbol: "NIO",
    },
    {
        id: 3561,
        name: "روپیه نپال",
        sign: "₨",
        symbol: "NPR",
    },
    {
        id: 3562,
        name: "ریال عمان",
        sign: "ر.ع.",
        symbol: "OMR",
    },
    {
        id: 3563,
        name: "بالبوآ پاناما",
        sign: "B/.",
        symbol: "PAB",
    },
    {
        id: 3564,
        name: "ریال قطر",
        sign: "«ر.ق»",
        symbol: "QAR",
    },
    {
        id: 3565,
        name: "دینار صربستان",
        sign: "din.",
        symbol: "RSD",
    },
    {
        id: 3566,
        name: "ریال عربستان",
        sign: "ر.س",
        symbol: "SAR",
    },
    {
        id: 3567,
        name: "پوند سودان جنوبی",
        sign: "£",
        symbol: "SSP",
    },
    {
        id: 3568,
        name: "دینار تونس",
        sign: "د.ت",
        symbol: "TND",
    },
    {
        id: 3569,
        name: "دلار ترینیداد و توباگو",
        sign: "$",
        symbol: "TTD",
    },
    {
        id: 3570,
        name: "شیلینگ اوگاندا",
        sign: "ش",
        symbol: "UGX",
    },
    {
        id: 3571,
        name: "پزوی اروگوئه",
        sign: "$",
        symbol: "UYU",
    },
    {
        id: 3572,
        name: "ازبکستان سوم",
        sign: "پس",
        symbol: "UZS",
    },
    {
        id: 3573,
        name: "بولیوار حاکم",
        sign: "Bs.",
        symbol: "VES",
    },]